gonzalezf fib.py
braxtonhall/fib pull request #20
Opened 2022-10-24 17:21 UTC by gonzalezf

- [ ] I added myself to [`people.json`](./people.json)!

2022-10-24 17:26 UTC, braxtonhall requested changes
JSON is dumb

2022-10-24 17:26 UTC, braxtonhall commented on people.json
> +        "title": "MSc Computer Science Student, UBC",
I assume this is a mistake!

2022-10-24 17:26 UTC, braxtonhall commented on people.json
> +        "title": "Assistant Professor of Computer Science, UBC",
As is this???

2022-10-24 17:26 UTC, braxtonhall commented on people.json
> +    {
line 190 will need a comma or the JSON will break :(

2022-10-24 23:32 UTC, wilbowma commented on people.json
> +        "title": "MSc Computer Science Student, UBC",
Dang doesn't even believe I have a PhD.

2022-10-25 03:01 UTC, gonzalezf commented on people.json
> +        "title": "Assistant Professor of Computer Science, UBC",
Oops, I went too far haha

2022-10-25 03:02 UTC, gonzalezf commented on people.json
> +        "title": "MSc Computer Science Student, UBC",
Oops, Sorry!

2022-10-25 03:12 UTC, closed without merging

2022-10-25 06:10 UTC, wilbowma commented on people.json
> +        "title": "MSc Computer Science Student, UBC",
Just trolling